### ISSUE TITLE
Allow to specify the desired compression level

### ISSUE THREAD

**Issue by imp** [mmstick/cargo-deb#108]
It seems the compression level is set to 9 (the highest possible) by default. Unfortunately for really big binaries (or debug info packages), this may result in the very long run (in my case it routinely takes over 10 minutes in one of my CI pipelines). It could be useful to be able to set the desired compression level externally. For example via a command line or environment variable.

**Comment by kornelski** [comment]
Indeed. This would also be useful for `--install` flag which doesn't even need to send the file anywhere.

This is even a bit more complicated: we use Zopfli, which is quite slow, and can't be configured to be fast. So we'd have to add another zlib library just to support faster compression.

Would you like to give it a try and add another compression lib as an option? Preferably a pure-rust one, so that cargo-deb remains easy to install.

**Comment by imp** [comment]
After having experimented with it for a while - it turned out that it is`xz` to blame.
It is just *unbelievably* slow. And it happen to be enabled by default when building `cargo-deb`. When enabled it takes precedence over `gz` compression for `data.tar`. BTW, while experimenting I've replaced `zopfli` with `flate2`, so all my results are based on `flate2` vs `xz2` crates.

To quantify my results - I've tested on quite a large Rust crate, which produces a few binaries.
Time it akes for `cargo deb` to build a `.deb` package:

`cargo deb` default build (compression level hardcoded to 9) - 10 minutes
Modified `cargo deb` that takes compression level  as an argument (run with 6) - 8.5 minutes
`cargo deb` w/o `lzma` feature - 58 seconds

So, with this in mind we can do a couple of different things:

1. Do nothing - recommend building with `--no-default-features` for those who care about time more than the space.
2. Add simple `--fast` flag that will choose `gz` compression when specified.
3. Add two flags `--gz [level]` and `--xz [level]` for maximum flexibility with desired compression algorithm and level.

What do you think?

**Comment by kornelski** [comment]
Oh, lzma is easier to change. 

I wouldn't expose numeric levels. I think it can be simplified to two cases: you either want best compression (because you archive/distribute it), or you don't (because you install it immediately, or use only internally).

So a `--fast` flag could be enough, and it could either disable lzma completely (data can be gzipped), or configure it to use fast compression.

**Comment by imp** [comment]
Would it be ok to rustfmt the whole crate? My IDE is configured to rustfmt on save by default and it is a pain to fight it all the time.

**Comment by kornelski** [comment]
Sorry, unconditional use of rustfmt is a hard no from me. It makes too many mistakes that make readability of the code worse.

**Comment by imp** [comment]
Got you. The rustfmt commit has been dropped

**Comment by imp** [comment]
1.22.0 now has `--fast` flag to prefer faster compression over smaller resulting archive size

**Comment by imp** [comment]
Can you please publish on crates.io?

**Comment by kornelski** [comment]
Done
