### ISSUE TITLE
Support for plain-text changelog

### ISSUE THREAD

**Issue by vorner** [mmstick/cargo-deb#73]
Hello

I understand debian wants to have compressed (`.gz`) changelogs in the package. However, it makes more sense to keep the changelog as plain text in my git repository. I actually do that and today I discovered that the `changelog.gz` file bundled inside is a plain text file, not a gzip archive.

Would it be possible to check if the changelog file is already compressed (maybe by looking at the file magic) and if not, compress it?

**Comment by kornelski** [comment]
I thought we always compress it, and only support plain text input.

**Comment by vorner** [comment]
At first I thought that too, but seeing this persuaded me 😇:

```
$ cd target/debian/
$ ls
control.tar.gz  data.tar.xz  debian-binary  skyline-pcaptain_0.1.8_amd64.deb
$ file control.tar.gz 
control.tar.gz: gzip compressed data, max compression, from Unix, original size 5120
$ tar xf data.tar.xz 
$ find -iname '*changelog*'
./usr/share/doc/skyline-pcaptain/changelog.gz
$ file ./usr/share/doc/skyline-pcaptain/changelog.gz
./usr/share/doc/skyline-pcaptain/changelog.gz: ASCII text
```

Should I try some older version than `1.12.0`?

**Comment by vorner** [comment]
Should I send a patch? Does what I propose at the top make sense, or should it actually mandate plaintext input (which is probably kind-of breaking change)?

**Comment by kornelski** [comment]
Sorry, I can't check the code now.

The intention is to:

* support only plaintext input (that's what has been proposed for Cargo).
* compress on the fly (so that the user never has to worry about doing it)
* after installation, have it stored compressed on the disk (that's what Debian recommends to save disk space)

Any deviation from this is a bug and fixes are welcome.
